version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: db-mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    # ports:
    #   - "3306:3306"
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.mysql.rule=HostSNI("*")
      - traefik.tcp.routers.mysql.entrypoints=mysql
      - traefik.tcp.services.mysql.loadbalancer.server.port=3306
    networks:
      - backend
    env_file:
      - ./.env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: db-phpmyadmin
    restart: unless-stopped
    # ports:
    #   - "8090:9010"
    environment:
      PMA_HOST: db-mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      APACHE_HTTP_PORT_NUMBER: 9010
    command: /bin/bash -c "sed -i \"s/80/$$APACHE_HTTP_PORT_NUMBER/g\" /etc/apache2/sites-available/000-default.conf /etc/apache2/ports.conf && /docker-entrypoint.sh apache2-foreground"
    labels:
      - traefik.enable=true
      - traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.${HOST}`)
      - traefik.http.services.phpmyadmin.loadbalancer.server.port=9010
      - traefik.http.routers.phpmyadmin.middlewares=authelia@docker
      # - traefik.http.routers.phpmyadmin.middlewares=mygeoblock@file
    depends_on:
      - mysql
    networks:
      - backend
    env_file:
      - ./.env

networks:
  backend:
    external: true