version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: db-mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    # # enable this to use traefik
#    labels:
#      - traefik.enable=true
#      - traefik.http.routers.mysql.rule=Host(`mysql.${HOST}`)
#      - traefik.http.routers.mysql.entrypoints=mysql
#      - traefik.http.services.mysql.loadbalancer.server.port=3306
#      - traefik.http.routers.mysql.middlewares=authelia@docker
    networks:
      - backend
    env_file:
      - ./.env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: db-phpmyadmin
    restart: unless-stopped
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db-mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
    networks:
      - backend
    env_file:
      - ./.env

networks:
  backend:
    external: true