version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "5050:9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.${HOST}`) || Host(`www.portainer.${HOST}`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.routers.portainer.middlewares=authelia@docker
    networks:
      - backend

volumes:
  data:

networks:
  backend:
    external: true
