version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "5050:9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - backend

volumes:
  data:

networks:
  backend:
    external: true
