version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    # ports:
    #   - "5050:9000"
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.${HOST}`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.routers.portainer.middlewares=authelia@docker
      # - traefik.http.routers.portainer.middlewares=mygeoblock@file
    networks:
      - backend

volumes:
  data:

networks:
  backend:
    external: true
