global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true
  debug: true

log:
  level: INFO
  # filepath: /var/log/traefik.log
  # accesslog: true
  # accesslog.filepath: /var/log/traefik-access.log

metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

# tracing:
#   jaeger:
#     localAgentHostPort: tr-jaeger:6831
#     samplingparam: 1.0
#     samplingServerURL: http://tr-jaeger:5778/sampling
#     samplingtype: const
#     propagation: jaeger

providers:
  docker:
    network: backend
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true

http:
  middlewares:
    ratelimit-be:
      rateLimit:
        average: 20
        period: 2m
        burst: 5
    ratelimit-docs:
      rateLimit:
        average: 30
        period: 1m
        burst: 20
    ratelimit-fe:
      rateLimit:
        average: 30
        period: 1m
        burst: 20

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    asDefault: true
    http:
      tls:
        certresolver: myresolver
  mysql:
    address: :3306
  sqlserver:
    address: :1433
  postgresql:
    address: :5432

certificatesResolvers:
  myresolver:
    acme:
      # email: {email}
      tlsChallenge: true
      storage: /letsencrypt/acme.json
