version: '3.9'

services:
  traefik:
    image: traefik:v3.0
    container_name: tr-traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - /etc/timezone:/etc/timezone
      # - /var/log:/var/log
    command:
      - --api.dashboard=true
      - --log.level=INFO
      # - --log.filepath=/var/log/traefik.log
      # - --accesslog=true
      #- --accesslog.filepath=/var/log/traefik-access.log
      - --providers.docker.network=backend
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entryPoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.asDefault=true
      - --entrypoints.websecure.http.tls.certresolver=myresolver
      - --certificatesresolvers.myresolver.acme.email=${EMAIL}
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    labels:
      - traefik.enable=true
      - traefik.http.routers.mydashboard.rule=Host(`traefik.${HOST}`)|| Host(`www.traefik.${HOST}`)
      - traefik.http.routers.mydashboard.service=api@internal
      - traefik.http.routers.mydashboard.middlewares=myauth
      # generate user and password
      # echo $(htpasswd -nbB USER "PASS") | sed -e s/\\$/\\$\\$/g
      # change USER and PASS
      # If htpasswd not found try to install "sudo apt install apache2-utils"
      - traefik.http.middlewares.myauth.basicauth.users=admin:$$2y$$05$$FJl67ipCWQ7AYK5W70oYNuuUmLw7nelQf9KjPd.Pd8XO6Sp3fU.5e
    env_file:
      - ./.env

  # whoami:
  #   image: traefik/whoami:v1.8
  #   container_name: tr-whoami
  #   networks:
  #     - backend
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.mywhoami.rule=Host(`whoami.${HOST}`) || Host(`www.whoami.${HOST}`)
  #     - traefik.http.services.mywhoami.loadbalancer.server.port=80
  #     - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
  #     - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
  #     - traefik.http.routers.mywhoami.middlewares=mywwwredirect

networks:
  backend:
    external: true
