version: '3.9'

services:
  traefik:
    image: traefik:v3.0
    container_name: tr-traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      # for db ports
      - "1433:1433"
      - "5432:5432"
      - "3306:3306"
      - "6379:6379"
      # - "6380:6380"
      - "5672:5672"
    networks:
      - backend
    environment:
      - TRAEFIK_CERTIFICATESRESOLVERS_MYRESOLVER_ACME_EMAIL=${EMAIL}
      - TZ=Asia/Jakarta
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${PWD}/config:/etc/traefik
      - ./logs:/var/log/traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.mydashboard.rule=Host(`traefik.${HOST}`)
      - traefik.http.routers.mydashboard.service=api@internal
      - traefik.http.routers.mydashboard.middlewares=myauth
      - traefik.http.middlewares.myauth.basicauth.users=${BASIC_AUTH}
      - traefik.http.routers.mydashboard.middlewares=authelia@docker
      # - traefik.http.routers.mydashboard.middlewares=mygeoblock@file
    env_file:
      - ./.env

#  jaeger:
#    image: jaegertracing/all-in-one:latest
#    container_name: tr-jaeger
#    restart: unless-stopped
#    volumes:
#      - "./jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
#    command: --query.ui-config /etc/jaeger/jaeger-ui.json
#    environment:
#      - METRICS_STORAGE_TYPE=prometheus
#      - PROMETHEUS_SERVER_URL=http://sm-prometheus:9090
#      - PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR=${PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR:-true}
#      - PROMETHEUS_QUERY_NAMESPACE=${PROMETHEUS_QUERY_NAMESPACE:-}
#      - PROMETHEUS_QUERY_DURATION_UNIT=${PROMETHEUS_QUERY_DURATION_UNIT:-}
#      - PROMETHEUS_QUERY_NORMALIZE_CALLS=true
#      - PROMETHEUS_QUERY_NORMALIZE_DURATION=true
#    ports:
#      # jaeger agent
#      - "6831:6831/udp"
#      # sampling
#      - "5778:5778"
#      # jaeger ui
#      - "16686:16686"
#    networks:
#      - backend

  # whoami:
  #   image: traefik/whoami:v1.8
  #   container_name: tr-whoami
  #   networks:
  #     - backend
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.mywhoami.rule=Host(`whoami.${HOST}`)
  #     - traefik.http.services.mywhoami.loadbalancer.server.port=80
  #     - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
  #     - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
  #     - traefik.http.routers.mywhoami.middlewares=mywwwredirect

networks:
  backend:
    external: true
