scrape_configs:
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['sm-node-exporter:9100']
  - job_name: 'traefik'
    scrape_interval: 5s
    static_configs:
      - targets: ['tr-traefik:8080']
