version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: db-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - data:/data
    command: '--requirepass ${REDIS_HOST_PASSWORD}'
    networks:
      - backend
    env_file:
      - ./.env

  redis-nopass:
    image: redis:latest
    container_name: db-redis-nopass
    restart: unless-stopped
    ports:
      - "6389:6379"
    volumes:
      - data-nopass:/data
    networks:
      - backend

  redisinsight:
    image: redislabs/redisinsight
    restart: unless-stopped
    container_name: db-redisinsight
    ports:
      - "8889:8001"
    depends_on:
      - redis
    networks:
      - backend

volumes:
  data:
  data-nopass:

networks:
  backend:
    external: true